services:
  api:
    image: rnjstngks/todo-api:v1
    ports: 
      - "4000:4000"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: