apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc  # PVC의 이름
spec:
  accessModes:
    - ReadWriteOnce  # 단일 노드에서 읽기/쓰기 가능
  resources:
    requests:
      storage: 1Gi  # 요청하는 스토리지 용량
  storageClassName: nfs-client