apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    app: nginx
    version: blue
  ports:
  - name: nginx-port
    protocol: TCP
    port: 80
    targetPort: http-web-svc