name: Ansible Playbook

on:
  workflow_run:
    workflows:
      - "Terraform Apply"
    types:
      - completed

jobs:
  ansible:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Wait for VM to initialize
        run: sleep 180

      - name: Run Ansible Playbook
        working-directory: /mnt/c/Users/Snetsystems/Documents/GitHub/DevOps-RoadMap/node.js-service-deployment/ansible
        run: ansible-playbook -i inventory.ini node_service.yml --tags "app"
