name: blue-green deployment

on:
  push:
    branches:
      - main
    paths:
      - "blue-green-deployment/dockerfile/*"
jobs:
  Blue-Gree_Deploy:
    runs-on: self-hosted # 내 Window 환경에서 Terraform 실행

    steps:
        # 코드 체크아웃
      - name: Check out Code
        uses: actions/checkout@v3

        # 이미지 빌드
      - name: Docker Build
        working-directory: /mnt/c/Users/Snetsystems/Documents/GitHub/DevOps-RoadMap/blue-green-deployment/dockerfile
        run: docker build -t rnjstngks/blue-green:${{ github.run_number }} .

        # 코드 체크아웃
      - name: Check out Code
        uses: actions/checkout@v3

        # DockerHub 로그인
      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_USERNAME }} # Docker Hub 사용자명
            password: ${{ secrets.DOCKER_PASSWORD }} # Docker Hub 비밀번호

        # 이미지 Push
      - name: Docker Push
        run: docker push rnjstngks/blue-green:${{ github.run_number }}

      - name: Change Image Tag
        working-directory: /mnt/c/Users/Snetsystems/Documents/GitHub/DevOps-RoadMap/blue-green-deployment
        run: |
          sed -i 's|image: rnjstngks/blue-green:.*|image: rnjstngks/blue-green:${{ github.run_number }}|g' rollout.yaml

      - name: Try pushing
        uses: dawidd6/action-git-try-push@v1
        with:
          # Optional, used for pushing
          token: ${{ secrets.TOKEN_GITHUB }}
          # Optional, defaults to current directory
          directory: /mnt/c/Users/Snetsystems/Documents/GitHub/DevOps-RoadMap/blue-green-deployment/
          # Optional, defaults to:
          remote: origin
          # Optional, defaults to:
          branch: main
          # Optional, defaults to:
          tries: 3