name: Deploy to GitHub Pages

# 작성된 deploy.yml 파일이 동작하기 위한 조건을 설정
# 즉, main 브랜치에 있는 index.html 파일이 Push 되었을 경우에 아래의 jobs를 실행 합니다.
on: 
  push:
    branches:
      - main # main 브랜치에서 푸시될 때만 실행
    paths:
      - "github-pages-deployment/index.html" # index.html 파일 변경 감지

jobs:
  deploy:
    runs-on: ubuntu-22.04 # Ubuntu 환경에서 실행

    steps:
      # 1. 저장소 체크아웃
      - name: Checkout Code
      # Github Action 에서 제공하는 플러그인 사용
      # actions/checkout@v3 : 저장소의 코드를 체크아웃 합니다.
        uses: actions/checkout@v3 

      # 2. 배포
      - name: Deploy to GitHub Pages
      # peaceiris/actions-gh-pages@v3 : Github Pages로 정적 파일을 배포하는 데 사용되는 플러그인
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github-pages-deployment # index.html이 저장소 루트에 있으므로 현재 디렉토리 배포