name: Dockerized Deployment

on:
  push:
    branches:
      - main
    paths:
      - "dockerized-service/Dockerfile/*"

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t rnjstngks/dockerized-service:v1 .
        docker push rnjstngks/dockerized-service:v1

    - name: SSH to server and deploy
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          docker pull rnjstngks/dockerized-service:v1
          docker stop nodejs-service || true
          docker rm nodejs-service || true
          docker run -d -p 3000:3000 --name nodejs-service rnjstngks/dockerized-service:v1
