name: Multi-Container Application

on:
  push:
    branches:
      - main
    paths:
      - "multi-container-application/app/*"
      - "multi-container-application/docker-compose.yml"

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      working-directory: /mnt/c/Users/Snetsystems/Documents/GitHub/DevOps-RoadMap/multi-container-application/app/
      run: |
        docker build -t rnjstngks/todo-api:v1 .
        docker push rnjstngks/todo-api:v1
        scp docker-compose.yml root@10.10.91.4:/root

    - name: SSH to server and deploy
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          docker pull rnjstngks/todo-api:v1
          docker compose up -d
