name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - "node.js-service-deployment/terraform/*.tf"

jobs:
  terraform:
    runs-on: self-hosted # 내 Window 환경에서 Terraform 실행

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.1

      - name: Terraform Init
        working-directory: node.js-service-deployment/terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: node.js-service-deployment/terraform
        run: terraform apply -auto-approve
