---
# 역할: MongoDB 데이터를 특정 디렉터리에 백업하는 작업

- name: Ensure backup directory exists
  # 백업 파일이 저장될 디렉터리를 생성
  file:
    path: /var/backups/mongo
    state: directory   # 디렉터리 상태를 유지
    mode: '0755'       # 권한 설정: 소유자 읽기/쓰기/실행, 그룹 및 다른 사용자 읽기/실행

- name: Add cron job to backup MongoDB every 12 hours
  # MongoDB 백업 작업을 크론 잡으로 등록
  cron:
    name: "MongoDB Backup"
    minute: "0"             # 매시 0분에 실행
    hour: "*/12"            # 12시간마다 실행 (오전 0시, 오후 12시 등)
    job: "mongodump --out /var/backups/mongo/$(date +%Y-%m-%d) --db jsondb "
  # 명령어 설명:
  # - 크론 잡은 정해진 시간에 명령어를 자동으로 실행
  # - `mongodump`를 통해 주기적으로 MongoDB를 백업
  # - 날짜 및 시간별로 디렉터리를 만들어 백업을 분리 저장
